name: Build and test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            cross: false
          - os: ubuntu-latest
            target: aarch64-unknown-linux-gnu
            cross: true
          - os: macos-latest
            target: x86_64-apple-darwin
            cross: false
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            cross: false

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2
    - name: Install appropriate toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true
        target: ${{ matrix.target }}
    - uses: actions-rs/cargo@v1
      name: Build
      with:
        command: build
        args: --target ${{ matrix.target }}
        use-cross: ${{ matrix.cross }}
    - uses: actions-rs/cargo@v1
      name: Build
      with:
        command: test
        args: --target ${{ matrix.target }}
        use-cross: ${{ matrix.cross }}
